Licenta/Licenta/Controllers/DetaliiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ClientNotifications;
using Licenta.Data;
using Licenta.Models;
using Licenta.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using static ClientNotifications.Helpers.NotificationHelper;

namespace Licenta.Controllers
{
    public class DetaliiController : Controller
    {
        private IDetaliiRepository _detaliiRepository;
        private UserManager<ApplicationUser> _userManager;

        public DetaliiController(UserManager<ApplicationUser> userManager,
                                    IDetaliiRepository detaliiRepository)
        {
            _detaliiRepository = detaliiRepository;
            _userManager = userManager;
        }
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var userId =  _userManager.GetUserId(HttpContext.User);
            var detaliis = await _detaliiRepository.GetDetaliiByUserId(userId);
            return View(detaliis);
        }


        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            ViewBag.IsEditMode = "false";
            var detalii = new Detalii();
            return View(detalii);
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(Detalii detalii, string IsEditMode)
        {

            try
            {
                if (IsEditMode.Equals("false"))
                {
                    var userId = _userManager.GetUserId(this.HttpContext.User);
                    detalii.UserId = userId;
                    await _detaliiRepository.Create(detalii);

                }
                else
                {
                    var userId = _userManager.GetUserId(this.HttpContext.User);
                    detalii.UserId = userId;
                    await _detaliiRepository.Edit(detalii);
                }
                   
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                return Content("Nu s-a putut crea sau edita inregistrarea!");
            }

        }

        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            var loggedInUserId = _userManager.GetUserId(HttpContext.User);

            ViewBag.IsEditMode = "true";
            var detalii = await _detaliiRepository.GetSingleDetalii(Id);
            if (!detalii.UserId.Equals(loggedInUserId))
            {
                return Content("Nu sunteti autorizat!");
            }
            return View("Create", detalii);
        }

        public async Task<IActionResult> Delete(int id)
        {
         
                var detalii = await _detaliiRepository.GetSingleDetalii(id);
                await _detaliiRepository.Delete(detalii);
                return RedirectToAction(nameof(Index));

        }

    }
}

Licenta/Licenta/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Licenta</title>
    <link href="~/lib/_vendor/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/bootstrap/dist/js/toastr.min.css" rel="stylesheet" />
    



</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Licenta</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Detalii" asp-action="Index">Evolutia Mea</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Tutoriale">Tutoriale</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Calculator">Calculator</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Licenta - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/_vendor/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/_vendor/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/_vendor/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/lib/sweetalert/sweetalert2.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/delete.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/toastr.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#jquery_jplayer_1").jPlayer({
                ready: function () {
                    $(this).jPlayer("setMedia", {
                        title: "test1",
                        //m4v: "http://www.jplayer.org/video/m4v/Big_Buck_Bunny_Trailer.m4v",
                        m4v: "C:/Users/EliteBook/Documents/GitHub/newLicenta/Facultate/Licenta/Licenta/wwwroot/videos/test1.m4a",
                        //ogv: "http://www.jplayer.org/video/ogv/Big_Buck_Bunny_Trailer.ogv",
                        poster: "http://www.jplayer.org/video/poster/Big_Buck_Bunny_Trailer_480x270.png",
                        //title: "Test",
                        //m4v: "/videos.test1.m4a"
                    }
                  );
                },
                cssSelectorAncestor: "#jp_container_1",
                swfPath: "/js",
                supplied: "m4v, ogv",
                useStateClassSkin: true,
                autoBlur: false,
                smoothPlayBar: true,
                keyEnabled: true,
                remainingDuration: true,
                toggleDuration: true
            });
        });</script>



    @RenderSection("Scripts", required: false)
</body>
</html>